version: '3.8'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    container_name: ros-master
    build: .
    tty: true
    working_dir: /workspase
    volumes:
      - .:/workspase
    env_file:
      - ./env/.env


  talker:
    build: .
    container_name: talker
    depends_on:
      - ros-master
    env_file:
      - ./env/.env
    command: ros2 run demo_nodes_cpp talker
    networks:
      - ros


  listener:
    build: .
    container_name: listener
    depends_on:
      - ros-master
    env_file:
      - ./env/.env
    command: ros2 run demo_nodes_py listener
    networks:
      - ros


  vis:
    build: .
    container_name: vis
    depends_on:
      - ros-master
    networks:
      - ros
    env_file:
      - ./env/.env
    user: ${UGID}
    command: rqt